// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emfgjcqbhucaygfspfjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtZmdqY3FiaHVjYXlnZnNwZmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODI2NDcsImV4cCI6MjA1OTY1ODY0N30.g5NAaOYAJb5sjpdIE48FzqFfjbLvzCdlQjy3r_8H9ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);